# Generated by Django 3.1.4 on 2020-12-15 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please write a brief description', max_length=200)),
                ('date', models.DateField(help_text='mm/dd/yyyy')),
                ('description', models.TextField(help_text='Please add a detailed description of your issue.')),
            ],
        ),
    ]
